### ISSUE TITLE
CreditCardMetadata missing in transaction

### ISSUE THREAD

**Issue by Mayco-Anderson** [pluggyai/pluggy-net#12]
Hi,

The creditCardMetadata is missing in the transaction model

Best Regards,
Mayco

**Comment by NicolasMontone** [comment]
Hey @Mayco-Anderson!
We will work to add this missing field this week! We will notify you 😄
Thanks for reporting this issue!

**Comment by NicolasMontone** [comment]
Hey @Mayco-Anderson, how are you doing? I already added the missing fields! Thanks for reporting, anything you need you can contact us via Slack or Intercom through our [Dashboard](https://dashboard.pluggy.ai/)!
Have a nice week!

**Comment by NicolasMontone** [comment]
Hey @Mayco-Anderson, how are you doing? I already added the missing fields! Thanks for reporting, anything you need you can contact us via Slack or Intercom through our [Dashboard](https://dashboard.pluggy.ai/)!
Have a nice week!
