### ISSUE TITLE
TransactionsParameters  has invalid PageSize parameter mapping

### ISSUE THREAD

**Issue by wdmatheus** [pluggyai/pluggy-net#14]
Accord with the [docs](https://docs.pluggy.ai/reference/transactions-list-1),  pagination parameters in list transactions endpoint has invalid page size mapping, currently is **size** while the api endpoint expects **pageSize**.

**Comment by NicolasMontone** [comment]
Hey @wdmatheus! We will fix it and let you know when it's done 😄 
Thanks a lot for the report!

**Comment by NicolasMontone** [comment]
Issue resolved in [#15](https://github.com/pluggyai/pluggy-net/pull/15)!
Thank you for reporting it @wdmatheus, anything you need, please get in touch with us! You can do it via Intercom in our [Dashboard](https://dashboard.pluggy.ai/)!
