### ISSUE TITLE
Missing fields

### ISSUE THREAD

**Issue by Mayco-Anderson** [pluggyai/pluggy-net#9]
I noticed that there are some fields that the API returns and is not mapped in the library, such as Merchant data in the Transactions model.

Is there any indication on when the changes in the API will be reflected in the SDK ?

Thanks in advance!

**Comment by Gabrielpanga** [comment]
Hey @Mayco-Anderson thanks for reporting this issue! It's correct the SDK its outdated for this response. We will be pushing an update this week with all latest changes. Please contact us through our [dashboard chat](https://dashboard.pluggy.ai) if this is a blocker for you!

**Comment by Mayco-Anderson** [comment]
Looking forward for the update and will reach out to you guys trough the dashboard chat. Thanks.

**Comment by NicolasMontone** [comment]
Hey @Mayco-Anderson! Thanks again for the report!
We already added the missing fields in this [PR](https://github.com/pluggyai/pluggy-net/pull/11)! Let us know if you need something else!
